# Site settings
title:          Lewis
description:    "The Little Lewis Family"
baseurl:        "/"
url:            "https://www.lewynandez.com"

theme: jekyll-theme-midnight
# Author
author:
  name:         Skyler Lewis
  url:          https://sixteenink.com
  #  email:        

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
