---
title: Lewis
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: The Little Lewis Family
baseurl: "/"
url: https://www.lewynandez.com
theme: jekyll-theme-midnight
author:
  name: Skyler Lewis
  url: https://sixteenink.com
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-paginate
permalink: "/:year-:month-:day/:title"
paginate: 5
